---
# These tasks install Nginx and start the Nginx server.

- name: Install Nginx
  yum: name={{ item }} state=present
  with_items:
    - nginx

- name: make sure nginx is running
  service: name=nginx state=started enabled=yes

- name: Configure Kibana for nginx
  template: src=nginx_kibana.conf.j2 dest=/etc/nginx/conf.d/default.conf mode=0644 #user=root group=root
  notify:
    - restart nginx