---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all

  roles:
    - common
    - mjp182.ntp

- name: deploy and configure the monitoring service
  hosts: monitor

  roles:
    - mjp182.java_jdk
    - mjp182.elasticsearch
    - mjp182.kibana
    - mjp182.nginx
    - mjp182.logstash

- name: deploy PostgreSQL and configure the databases and users
  hosts: db

  roles:
    - mjp182.postgreSQL
    - mjp182.logstash-forwarder 

- name: configure and deploy the web server and app server
  hosts: web1

  roles:
    - mjp182.nginx
    - mjp182.rbenv_ruby
    - mjp182.postgres_client
    - mjp182.logstash-forwarder 