---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all

  roles:
    - common
    - ntp

- name: deploy and configure the monitoring service
  hosts: monitor

  roles:
    - java_jdk
    - elasticsearch
    - kibana
    - nginx
    - logstash

- name: deploy PostgreSQL and configure the databases and users
  hosts: db

  roles:
    - PostgreSQL
    - logstash-forwarder 

- name: configure and deploy the web server and app server
  hosts: web1

  roles:
    - nginx
    - rbenv_ruby
    - postgres_client
    - logstash-forwarder 