---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all

  roles:
    - common
#    - client_local_repo
#    - ntp

- name: deploy and configure the monitoring service
  hosts: monitor

  roles:
    - go
    - java
    - elastic
    - kibana
    - nginx
    - logstash

- name: deploy PostgreSQL and configure the databases and users
  hosts: db

  roles:
    - go
    - pg
    - logstash-forwarder 

- name: configure and deploy the web server and app server
  hosts: web1

  roles:
    - go  
    - nginx
#    - ruby_source
    - pg_client
    - logstash-forwarder 