---
galaxy_info:
  author: mjp182
  description: Use git to manage projects.
  company: your company (optional)
  license: license (MIT)
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - 6
    - 7

  categories:
  - development

dependencies: []