---
- name: Install Ruby - install dependencies
  yum: name={{ item }} state=present
  with_items:
    - wget 
    - git 
    - gcc 
    - openssl-devel 
    - readline-devel 
    - zlib-devel 
    - libyaml-devel 
    - gcc-c++ 
    - patch 
    - automake 
    - libtool 
    - bison 
    - libffi-devel

- name: Download Ruby tarball
  get_url: url={{ruby_source_IP}} dest=/tmp

- name: Unpack Ruby tarball
  unarchive: src=/tmp/ruby-{{ruby_version}}.tar.gz dest=/home/vagrant/ copy=no

- name: Configure Ruby
  command: ./configure --enable-shared --disable-install-doc
  args:
    chdir: /home/vagrant/ruby-{{ruby_version}}

- name: Make Ruby
  command: make
  args:
    chdir: /home/vagrant/ruby-{{ruby_version}}

- name: Install Ruby
  command: make install
  args:
    chdir: /home/vagrant/ruby-{{ruby_version}}

- name: Add ruby symlinks.
  file: >
    src=/usr/local/bin/{{ item }}
    dest=/usr/bin/{{ item }}
    state=link
  with_items:
    - erb
    - gem
    - irb
    - rake
    - rdoc
    - ruby

- name: Don't install documentation with gems
  template: src=gem_config.conf.j2 dest=/home/vagrant/.gemrc

- name: Install the Bundler gem
  gem: name=bundler state=present user_install=no

- name: Add bundle symlink
  file: src=/usr/local/bin/bundle dest=/usr/bin/bundle state=link