---
- name: Install Ruby - install dependencies
  yum: name={{ item }} state=present 
  with_items:
    - wget 
    - git 
    - gcc 
    - openssl-devel 
    - readline-devel 
    - zlib-devel 
    - libyaml-devel 
    - gcc-c++ 
    - patch 
    - automake 
    - libtool 
    - bison 
    - libffi-devel

- name: Download Ruby source
  get_url: url=http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.0.tar.gz dest=/tmp

- name: Unpack Ruby tarball
  unarchive: src=/tmp/ruby-2.2.0.tar.gz dest=/home/vagrant/ copy=no

- name: Configure Ruby
  raw: /home/vagrant/ruby-2.0.0/configure

- name: Make Ruby
  command: make
  args:
    chdir: /home/vagrant/ruby-2.0.0

- name: Install Ruby
  command: make install
  args:
    chdir: /home/vagrant/ruby-2.0.0