---
- name: Install Ruby - install dependencies
  yum: name={{ item }} state=present 
  with_items:
    - wget 
    - git 
    - gcc 
    - openssl-devel 
    - readline-devel 
    - zlib-devel 
    - libyaml-devel 
    - gcc-c++ 
    - patch 
    - automake 
    - libtool 
    - bison 
    - libffi-devel

- name: Download Ruby source
  get_url: url=http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.0.tar.gz dest=/tmp

- name: Unpack Ruby tarball
  unarchive: src=/tmp/ruby-2.2.0.tar.gz dest=/home/vagrant/ copy=no

- name: Configure Ruby
  command: ./configure --enable-shared
  args:
    chdir: /home/vagrant/ruby-2.2.0

- name: Make Ruby
  command: make
  args:
    chdir: /home/vagrant/ruby-2.2.0

- name: Install Ruby
  command: make install
  args:
    chdir: /home/vagrant/ruby-2.2.0

- name: Add ruby symlinks.
  file: >
    src=/usr/local/bin/{{ item }}
    dest=/usr/bin/{{ item }}
    state=link
  with_items:
    - erb
    - gem
    - irb
    - rake
    - rdoc
    - ruby

- name: Install the Bundler gem
  gem: name=bundler state=present user_install=no

- name: Add bundle symlink
  file: src=/usr/local/bin/bundle dest=/usr/bin/bundle state=link