---
# initialize, start, and configure PostgreSQL

- name: Check whether PG cluster is already initialized
  command: >
    systemctl status postgresql-9.4 -l
  register: data_dir
  ignore_errors: true

- name: Initialize the database cluster
  command: /usr/pgsql-9.4/bin/postgresql94-setup initdb
  when: "'inactive (dead)' in data_dir.stdout"

- name: Start PostgreSQL and enable on boot
  service: name=postgresql-9.4 state=started enabled=yes

- name: Create project database
  sudo_user: postgres
  postgresql_db: name={{ pg_remote_db_name }}

- name: Create postgresql user
  sudo_user: postgres 
  postgresql_user: 
    db: "{{ pg_remote_db_name }}"
    name: "{{ pg_remote_user }}"
    password: "{{ pg_remote_user_password }}"
    priv: ALL

- name: Ensure user has the right privileges
  sudo_user: postgres
  postgresql_user: name={{ pg_remote_user }} role_attr_flags=CREATEDB,NOSUPERUSER

- name: Copy postgresql client authentication config to server
  sudo: yes
  template: src=pg_hba.conf.j2 dest=/var/lib/pgsql/9.4/data/pg_hba.conf

- name: Copy postgresql configuration file to server
  sudo: yes
  template: src=postgresql.conf.j2 dest=/var/lib/pgsql/9.4/data/postgresql.conf
  notify: 
    - restart postgresql-9.4