---
galaxy_info:
  author: Matthew Pontes
  description: Install the PostgreSQL client on CentOS 7
  company: your company (optional)
  license: license (MIT)
  min_ansible_version: 1.2

  platforms:
  - name: EL
    versions:
    - 7

  categories:
  - database
  - database:sql

dependencies: []
